// This file is auto-generated by @hey-api/openapi-ts

export type AccessTokenResponse = {
    readonly tokenType?: (string) | null;
    accessToken: (string) | null;
    expiresIn: number;
    refreshToken: (string) | null;
};

export type ForgotPasswordRequest = {
    email: (string) | null;
};

export type HttpValidationProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
    errors?: {
        [key: string]: Array<(string)>;
    } | null;
    [key: string]: (unknown | string | number) | undefined;
};

export type InfoRequest = {
    newEmail?: (string) | null;
    newPassword?: (string) | null;
    oldPassword?: (string) | null;
};

export type InfoResponse = {
    email: (string) | null;
    isEmailConfirmed: boolean;
};

export type LoginRequest = {
    email: (string) | null;
    password: (string) | null;
    twoFactorCode?: (string) | null;
    twoFactorRecoveryCode?: (string) | null;
};

export type RefreshRequest = {
    refreshToken: (string) | null;
};

export type RegisterRequest = {
    email: (string) | null;
    password: (string) | null;
};

export type ResendConfirmationEmailRequest = {
    email: (string) | null;
};

export type ResetPasswordRequest = {
    email: (string) | null;
    resetCode: (string) | null;
    newPassword: (string) | null;
};

export type TodoItemDeletionResponse = {
    success?: boolean;
    errorMessage?: (string) | null;
};

export type TodoItemDTO = {
    id?: number;
    title: (string) | null;
    isComplete?: boolean;
    description?: (string) | null;
    dueDate?: (string) | null;
    createdAt?: string;
    updatedAt?: string;
    isDeleted?: (boolean) | null;
    deletedAt?: (string) | null;
};

export type TodoItemResponse = {
    success?: boolean;
    errorMessage?: (string) | null;
    data?: TodoItemDTO;
};

export type TodoItemsMultipleResponse = {
    success?: boolean;
    errorMessage?: (string) | null;
    data?: Array<TodoItemDTO> | null;
};

export type TwoFactorRequest = {
    enable?: (boolean) | null;
    twoFactorCode?: (string) | null;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: (string) | null;
    recoveryCodesLeft: number;
    recoveryCodes?: Array<(string)> | null;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type UserDto = {
    id: (string) | null;
    email?: (string) | null;
    emailConfirmed: boolean;
    phoneNumber?: (string) | null;
    phoneNumberConfirmed: boolean;
};

export type PostApiAuthRegisterData = {
    body: RegisterRequest;
};

export type PostApiAuthRegisterResponse = (unknown);

export type PostApiAuthRegisterError = (HttpValidationProblemDetails);

export type PostApiAuthLoginData = {
    body: LoginRequest;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
};

export type PostApiAuthLoginResponse = (AccessTokenResponse);

export type PostApiAuthLoginError = unknown;

export type PostApiAuthRefreshData = {
    body: RefreshRequest;
};

export type PostApiAuthRefreshResponse = (AccessTokenResponse);

export type PostApiAuthRefreshError = unknown;

export type MapIdentityApiApiAuthConfirmEmailData = {
    query: {
        changedEmail?: string;
        code: string;
        userId: string;
    };
};

export type MapIdentityApiApiAuthConfirmEmailResponse = (unknown);

export type MapIdentityApiApiAuthConfirmEmailError = unknown;

export type PostApiAuthResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
};

export type PostApiAuthResendConfirmationEmailResponse = (unknown);

export type PostApiAuthResendConfirmationEmailError = unknown;

export type PostApiAuthForgotPasswordData = {
    body: ForgotPasswordRequest;
};

export type PostApiAuthForgotPasswordResponse = (unknown);

export type PostApiAuthForgotPasswordError = (HttpValidationProblemDetails);

export type PostApiAuthResetPasswordData = {
    body: ResetPasswordRequest;
};

export type PostApiAuthResetPasswordResponse = (unknown);

export type PostApiAuthResetPasswordError = (HttpValidationProblemDetails);

export type PostApiAuthManage2FaData = {
    body: TwoFactorRequest;
};

export type PostApiAuthManage2FaResponse = (TwoFactorResponse);

export type PostApiAuthManage2FaError = (HttpValidationProblemDetails | unknown);

export type GetApiAuthManageInfoResponse = (InfoResponse);

export type GetApiAuthManageInfoError = (HttpValidationProblemDetails | unknown);

export type PostApiAuthManageInfoData = {
    body: InfoRequest;
};

export type PostApiAuthManageInfoResponse = (InfoResponse);

export type PostApiAuthManageInfoError = (HttpValidationProblemDetails | unknown);

export type PostApiAuthLogoutData = {
    body?: unknown;
};

export type PostApiAuthLogoutResponse = (unknown);

export type PostApiAuthLogoutError = unknown;

export type GetApiAuthMeResponse = (UserDto);

export type GetApiAuthMeError = (unknown);

export type GetApiTodoItemsResponse = (TodoItemResponse);

export type GetApiTodoItemsError = unknown;

export type PostApiTodoItemsData = {
    body?: TodoItemDTO;
};

export type PostApiTodoItemsResponse = (TodoItemResponse);

export type PostApiTodoItemsError = unknown;

export type GetApiTodoItemsByIdData = {
    path: {
        id: number;
    };
};

export type GetApiTodoItemsByIdResponse = (TodoItemResponse);

export type GetApiTodoItemsByIdError = unknown;

export type PutApiTodoItemsByIdData = {
    body?: TodoItemDTO;
    path: {
        id: number;
    };
};

export type PutApiTodoItemsByIdResponse = (unknown);

export type PutApiTodoItemsByIdError = unknown;

export type DeleteApiTodoItemsByIdData = {
    body?: boolean;
    path: {
        id: number;
    };
};

export type DeleteApiTodoItemsByIdResponse = (TodoItemDeletionResponse);

export type DeleteApiTodoItemsByIdError = unknown;

export type PostApiTodoItemsBulkData = {
    body?: Array<TodoItemDTO>;
};

export type PostApiTodoItemsBulkResponse = (TodoItemsMultipleResponse);

export type PostApiTodoItemsBulkError = unknown;